FROM mcr.microsoft.com/dotnet/sdk:9.0

RUN apt-get update && apt-get install -y default-mysql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy solution and projects (no build here)
COPY . ./

# RUN dotnet tool install -g dotnet-ef
# ENV PATH="$PATH:/root/.dotnet/tools"
# Restore tools (if using dotnet-ef)
# RUN dotnet tool restore