services:
  test-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservations
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    networks:
      - test-net

  test-runner:
    build: 
      context: .
      dockerfile: dockerfile.test
    working_dir: /app
    depends_on:
      - test-mysql
    volumes:
      - ./jenkins-artifacts:/app/coverage
    networks:
      - test-net
    command: >
      /bin/sh -c "
      until mysqladmin ping -h test-mysql --silent; do
        echo 'Waiting for MySQL to be ready...';
        sleep 2;
      done
      &&
      dotnet restore ReservationAPI.sln &&
      dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=/app/coverage/coverage.cobertura.xml --logger 'console;verbosity=detailed'
      "

volumes:
  build-cache:

networks:
  test-net: