FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

# Copy solution and projects (no build here)
COPY . ./

# RUN dotnet tool install -g dotnet-ef
# ENV PATH="$PATH:/root/.dotnet/tools"
# Restore tools (if using dotnet-ef)
# RUN dotnet tool restore