services:
  test-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservations
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    networks:
      - test-net

  test-runner:
    build: 
      context: .
      dockerfile: dockerfile.test
    working_dir: /app
    depends_on:
      - test-mysql
    networks:
      - test-net
    command: >
      /bin/sh -c "
      until ping -c 1 test-mysql > /dev/null 2>&1; do
        echo 'Waiting for MySQL container to be reachable...';
        sleep 2;
      done;
      echo 'MySQL container reachable, waiting a few more seconds...';
      sleep 5;
      dotnet restore ReservationAPI.sln &&
      dotnet test --logger 'console;verbosity=detailed'
      "

volumes:
  build-cache:

networks:
  test-net: