services:
  test-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservations
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    networks:
      - test-net

  test-runner:
    build: 
      context: .
      dockerfile: dockerfile.test
    working_dir: /app
    depends_on:
      - test-mysql
    networks:
      - test-net
    command: >
      /bin/sh -c "
      dotnet restore ReservationAPI.sln &&
      dotnet test --logger 'console;verbosity=detailed'
      "

volumes:
  build-cache:

networks:
  test-net: